#!/usr/bin/env python3
"""
preflight.py — could every agent complete a cycle if it woke right now?

health-check.py answers a different question: DID they run. It compares
systemd, disk and the Deck after the fact. That is the right tool for "is the
dashboard lying", and it is why Scout was cleared.

It cannot tell you an agent is about to fail. Everything that actually broke
this month was invisible to it and visible here:

  * Ace's instructions said `ace-judge.py mark`. There was no `mark`
    subcommand. Ace improvised, hand-edited bankroll.json in a loop and
    timed out. Three cycles lost to a command that did not exist.
  * OpenRouter credit ran out. Every wake failed instantly, all week,
    and the agents looked idle rather than broken.
  * AGENTS.md drifted behind its header, so agents ran last week's rules
    while the repo said otherwise.

Each of those is a fact on disk or one free HTTP call away. None of them
needs a model to notice, so this spends nothing and can be run as often as
you like - before a deploy, after editing instructions, or any time you want
to know the ecosystem is armed.

    python3 scripts/preflight.py             # every agent
    python3 scripts/preflight.py ace belfort # just these

Exit code 1 if anything would stop a cycle. Warnings alone exit 0.

Read-only except for nothing at all: it changes no file and wakes no model.
"""

import importlib.util
import json
import os
import re
import subprocess
import sys
import urllib.request
from pathlib import Path

ROOT = Path(os.environ.get("ECOSYSTEM_ROOT", Path(__file__).resolve().parent.parent))
AGENTS = ROOT / "agents"
SCRIPTS = ROOT / "scripts"

# systemd handling, unit lookup and the "systemctl is not answering" rule live
# in health-check.py. Restating them here would give the project two opinions
# about whether a timer is installed, and those drift - the report filename,
# the sign-off freshness rule and the balance identity all drifted exactly
# that way before they were pulled into one place.
_spec = importlib.util.spec_from_file_location("healthcheck", SCRIPTS / "health-check.py")
hc = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(hc)

BLOCK, WARN = [], []
UNDEPLOYED = []


def block(agent, msg, fix=""):
    BLOCK.append((agent, msg, fix))


def warn(agent, msg, fix=""):
    WARN.append((agent, msg, fix))


# --------------------------------------------------------------------------
# instructions
# --------------------------------------------------------------------------

# Matches `scripts/ace-judge.py mark` wherever it appears, including inside
# `python3 ../../scripts/ace-judge.py mark`. The subcommand must start with a
# letter so that `ace-verify.py 1234` (a positional timestamp) is not read as
# one, and flags are excluded by the character class.
CMD_RE = re.compile(r"scripts/([a-z0-9_-]+\.py)\s+([a-z][a-z0-9-]*)")

_subs_cache = {}


def subcommands(script):
    """The subcommands argparse will accept, or None if the script has none.

    Taken from --help rather than by reading the source: every one of these
    scripts builds its parser inside main(), so the source says nothing a
    regex can trust, while --help is argparse's own answer and exits before
    the script does any work.
    """
    if script in _subs_cache:
        return _subs_cache[script]
    subs = None
    try:
        out = subprocess.run([sys.executable, str(SCRIPTS / script), "--help"],
                             capture_output=True, text=True, timeout=30).stdout
        # argparse prints its subparser choices as {list,show,pass,...}.
        for group in re.findall(r"\{([a-z0-9_,-]+)\}", out):
            if "," in group:
                subs = set(group.split(","))
                break
    except Exception:
        pass
    _subs_cache[script] = subs
    return subs


def check_instructions(name, adir):
    md = adir / "AGENTS.md"
    header = adir / f"_{name}-agents-header.md"

    if not md.is_file():
        # AGENTS.md is generated by merge-header.sh and deliberately untracked,
        # so a fresh clone has none. That is one fact about the checkout, not a
        # separate failure per agent - main() collapses it.
        UNDEPLOYED.append(name)
        block(name, "AGENTS.md does not exist - the agent wakes with no instructions",
              f"scripts/merge-header.sh {name}")
        return
    if header.is_file() and header.stat().st_mtime > md.stat().st_mtime:
        block(name, "the instruction header is newer than AGENTS.md - the agent "
                    "is running stale rules",
              f"scripts/deploy.sh {name}")

    text = md.read_text()
    if header.is_file() and f"BEGIN {name}-header" not in text:
        warn(name, "AGENTS.md carries no header markers, so nothing can rebuild it "
                   "unattended", f"scripts/merge-header.sh {name}")

    # THE ace-judge mark BUG. Every command the instructions tell the agent to
    # run, checked against what the script will actually accept.
    for script, sub in set(CMD_RE.findall(text)):
        path = SCRIPTS / script
        if not path.is_file():
            block(name, f"AGENTS.md tells it to run scripts/{script}, which does not exist")
            continue
        subs = subcommands(script)
        if subs is not None and sub not in subs:
            block(name, f"AGENTS.md says `{script} {sub}` but that subcommand does "
                        f"not exist (it has: {', '.join(sorted(subs))})")


# --------------------------------------------------------------------------
# the scripts a cycle runs
# --------------------------------------------------------------------------

def check_cycle_chain(name):
    """Does the wrapper exist, and does everything it calls still compile?

    A syntax error in a verifier is not found at edit time - it is found
    hours later, by the timer, after the model call has already been paid for.
    """
    wrapper = SCRIPTS / f"{name}-cycle.sh"
    if not wrapper.is_file():
        return  # not every agent is timer-driven; the unit check covers that.

    text = wrapper.read_text()
    for script in sorted(set(re.findall(r"([a-z0-9_-]+\.py)", text))):
        path = SCRIPTS / script
        if not path.is_file():
            block(name, f"{name}-cycle.sh calls scripts/{script}, which does not exist")
            continue
        r = subprocess.run([sys.executable, "-m", "py_compile", str(path)],
                           capture_output=True, text=True)
        if r.returncode != 0:
            first = (r.stderr.strip().splitlines() or ["?"])[-1]
            block(name, f"scripts/{script} does not compile - the cycle will die "
                        f"after the model call: {first}")


# --------------------------------------------------------------------------
# scheduling
# --------------------------------------------------------------------------

def check_schedule(name):
    if not (ROOT / "deploy" / f"{name}-cycle.service").is_file():
        return  # on demand by design - Emily is woken by the task queue.
    if not hc.HAVE_SYSTEMD:
        return  # health-check already said why the timer column is blank.

    _, _, load = hc.unit_facts(f"{name}-cycle.service")
    if load == "not-found":
        block(name, f"{name}-cycle.service is not installed - nothing can wake it",
              f"scripts/deploy.sh {name}")
    elif not hc.timer_next(f"{name}-cycle.timer"):
        block(name, f"{name}-cycle.timer is not active - the unit exists but will "
                    f"never fire", f"systemctl enable --now {name}-cycle.timer")


# --------------------------------------------------------------------------
# credentials
# --------------------------------------------------------------------------

def check_credentials(name, adir):
    """Only reports; check-credentials.py is the tool that explains and repairs."""
    path = adir / "state" / "credentials.env"
    example = adir / "state" / "credentials.env.example"
    if not path.is_file():
        if example.is_file():
            warn(name, "state/credentials.env does not exist, but the example does",
                 f"python3 scripts/check-credentials.py {name}")
        return

    empty = []
    for line in path.read_text().splitlines():
        s = line.strip()
        if not s or s.startswith("#") or "=" not in s:
            continue
        k, v = s.split("=", 1)
        if not v.strip().strip('"').strip("'"):
            empty.append(k.strip())
    if empty:
        warn(name, f"credentials set but empty: {', '.join(empty)}",
             f"python3 scripts/check-credentials.py {name}")


# --------------------------------------------------------------------------
# the model, and whether there is money behind it
# --------------------------------------------------------------------------

def openrouter_key():
    key = os.environ.get("OPENROUTER_API_KEY", "").strip()
    if key:
        return key
    # The agents share one key; whichever file has it will do.
    for f in sorted(AGENTS.glob("*/state/credentials.env")):
        for line in f.read_text().splitlines():
            if line.strip().startswith("OPENROUTER_API_KEY="):
                v = line.split("=", 1)[1].strip().strip('"').strip("'")
                if v:
                    return v
    return ""


def check_credit():
    """OpenRouter's key endpoint reports the balance and runs no inference.

    This is the check that would have named the week Ace failed every single
    wake: the key was valid, the model was right, the credit was gone, and
    from the outside that is indistinguishable from an idle agent.
    """
    key = openrouter_key()
    if not key:
        print("credit     no OPENROUTER_API_KEY found - skipped")
        return
    try:
        req = urllib.request.Request("https://openrouter.ai/api/v1/key",
                                     headers={"Authorization": f"Bearer {key}"})
        with urllib.request.urlopen(req, timeout=20) as r:
            d = json.loads(r.read()).get("data") or {}
    except Exception as exc:
        warn("-", f"could not read the OpenRouter balance ({exc})")
        print("credit     unreadable")
        return

    limit, usage = d.get("limit"), d.get("usage") or 0
    if limit is None:
        print(f"credit     ${usage:.2f} used, no cap set")
        return
    left = limit - usage
    print(f"credit     ${left:.2f} left of ${limit:.2f}")
    if left <= 0:
        BLOCK.append(("-", "OpenRouter credit is exhausted - every wake will fail "
                           "instantly and the agents will look idle",
                      "top up at openrouter.ai/credits"))
    elif left < 2:
        warn("-", f"OpenRouter credit is down to ${left:.2f}")


_catalogue = None


def in_catalogue(slug):
    global _catalogue
    if _catalogue is None:
        try:
            with urllib.request.urlopen("https://openrouter.ai/api/v1/models", timeout=30) as r:
                _catalogue = {m["id"] for m in json.loads(r.read())["data"]}
        except Exception:
            _catalogue = set()
    if not _catalogue:
        return None
    return slug.removeprefix("openrouter/") in _catalogue


def agent_model(name):
    if not shutil_which("openclaw"):
        return None
    out = subprocess.run(["openclaw", "config", "get",
                          f"agents.entries.{name}.model.primary"],
                         capture_output=True, text=True, timeout=30).stdout
    m = re.search(r"[\w.-]+/[\w.:-]+", out)
    return m.group(0) if m else None


def shutil_which(b):
    from shutil import which
    return which(b)


def check_model(name):
    slug = agent_model(name)
    if not slug:
        return None
    # A wrong slug does not fail loudly. The agent simply reports "model not
    # found" at its next wake, hours later, with the cycle lost.
    ok = in_catalogue(slug)
    if ok is False:
        block(name, f"model '{slug}' is not in OpenRouter's catalogue - the wake "
                    f"will fail with 'model not found'",
              f"scripts/set-agent-model.sh {name} <slug> --apply")
    return slug


# --------------------------------------------------------------------------

def main():
    hc.HAVE_SYSTEMD = subprocess.run(["systemctl", "is-system-running"],
                                     capture_output=True, text=True
                                     ).stdout.strip() not in ("", "offline", "unknown")

    wanted = [a for a in sys.argv[1:] if not a.startswith("-")]
    names = sorted(d.name for d in AGENTS.iterdir()
                   if d.is_dir() and not d.name.startswith("."))
    if wanted:
        names = [n for n in names if n in wanted]

    print("preflight - could each agent complete a cycle if it woke now?")
    print("no model is called, so this costs nothing.\n")

    # Run from a laptop clone rather than the droplet, most of this is
    # unknowable. Say which parts, so a blank column is not read as a finding.
    if not shutil_which("openclaw"):
        print("note: openclaw is not on PATH, so the model column is unknown,")
        print("      not empty. Run this on the droplet for those checks.\n")
    elif not hc.HAVE_SYSTEMD:
        print("note: systemctl is not answering, so the schedule column is")
        print("      unknown, not a finding.\n")

    print(f"{'agent':<10}{'model':<34}{'instructions':<14}{'schedule':<12}")
    print("-" * 70)

    for name in names:
        adir = AGENTS / name
        if (adir / "RETIRED").is_file():
            print(f"{name:<10}{'retired':<34}{'-':<14}{'-':<12}")
            continue

        before = len(BLOCK)
        check_instructions(name, adir)
        instr = "stale/broken" if len(BLOCK) > before else "current"

        before = len(BLOCK)
        check_cycle_chain(name)
        check_schedule(name)
        if not (ROOT / "deploy" / f"{name}-cycle.service").is_file():
            sched = "on demand"
        elif len(BLOCK) > before:
            sched = "broken"
        elif not hc.HAVE_SYSTEMD:
            # check_schedule returned without looking at anything. Printing
            # "armed" here would be the column inventing a fact.
            sched = "unknown"
        else:
            sched = "armed"

        check_credentials(name, adir)
        slug = check_model(name) or ("unknown" if not shutil_which("openclaw") else "not set")
        print(f"{name:<10}{slug:<34}{instr:<14}{sched:<12}")

    print()
    check_credit()
    print()

    live = [n for n in names if not (AGENTS / n / "RETIRED").is_file()]
    if UNDEPLOYED and len(UNDEPLOYED) == len(live):
        BLOCK[:] = [b for b in BLOCK if "AGENTS.md does not exist" not in b[1]]
        BLOCK.insert(0, ("-", "no agent has an AGENTS.md, so this checkout has never "
                              "been deployed - AGENTS.md is generated, not tracked",
                         "scripts/deploy.sh --all"))

    for label, items in (("WOULD STOP A CYCLE", BLOCK), ("WORTH KNOWING", WARN)):
        if items:
            print(label)
            for agent, msg, *fix in items:
                who = f"{agent}: " if agent != "-" else ""
                print(f"  - {who}{msg}")
                if fix and fix[0]:
                    print(f"      fix: {fix[0]}")
            print()

    if not BLOCK:
        print("Nothing would stop a cycle. Whether the model finishes one is a")
        print("separate question and only a real wake answers it.")
    return 1 if BLOCK else 0


if __name__ == "__main__":
    sys.exit(main())
